services:
  reconcile-api:
    build: .
    container_name: reconcile-api
    ports:
      - "8001:8001"
    volumes:
      - type: bind
        source: ./config.py
        target: /openrefine-wikibase1/config.py
        read_only: true
  reconcile-valkey:
    image: "valkey/valkey:alpine"
    expose:
      - "6379" 
