services:
  reconcile:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - type: bind
        source: ./config.py
        target: /openrefine-wikibase1/config.py
        read_only: true
  redis:
    image: "valkey/valkey:alpine"
    expose:
      - "6379" 
